cmake -DCMAKE_BUILD_TYPE=DEBUG -DWITH_FFMPEG=ON\
 -DBUILD_TESTS=OFF -DBUILD_PREF_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF\
 -DWITH_IPP=OFF -DWITH_TBB=OFF -DWITH_OPENMP=OFF -DWITH_PTHREADS_PF=OFF\
 -DWITH_CUDA=OFF \
-DBUILD_OPENCV_PYTHON3=OFF -DBUILD_OPENCV_PYTHON2=OFF\
 -S. -B/opencv_build

#-DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules 

