cmake -DCMAKE_BUILD_TYPE=DEBUG -DWITH_FFMPEG=ON -DWITH_AVFOUNDATION=OFF \
 -DBUILD_TESTS=OFF -DBUILD_PREF_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF\
 -DWITH_IPP=OFF -DWITH_TBB=OFF -DWITH_OPENMP=OFF -DWITH_PTHREADS_PF=OFF\
 -DWITH_CUDA=OFF \
-DBUILD_OPENCV_PYTHON3=OFF -DBUILD_OPENCV_PYTHON2=OFF\
 -DOPENCV_EXTRA_MODULES_PATH=/Users/liuziang/Downloads/opencv_contrib-4.5.1/modules/ \
 -S. -Bopencv_build

